import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f2f4f7',
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: {width: 0, height: 4},
    elevation: 2,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#101828',
  },
  subtitle: {
    marginTop: 4,
    marginBottom: 16,
    fontSize: 14,
    color: '#475467',
  },
  label: {
    marginTop: 10,
    marginBottom: 6,
    color: '#344054',
    fontWeight: '600',
  },
  input: {
    borderWidth: 1,
    borderColor: '#d0d5dd',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: '#101828',
    backgroundColor: '#fff',
  },
  button: {
    marginTop: 14,
    borderRadius: 10,
    paddingVertical: 12,
    backgroundColor: '#175cd3',
    alignItems: 'center',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 15,
  },
  mockOtp: {
    marginTop: 8,
    fontSize: 13,
    color: '#667085',
  },
  errorText: {
    marginTop: 6,
    color: '#b42318',
    fontSize: 12,
  },
  homeContainer: {
    padding: 20,
    gap: 14,
  },
  homeTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#101828',
  },
  homeSubtitle: {
    color: '#475467',
    marginBottom: 4,
  },
  homeCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: {width: 0, height: 3},
    elevation: 2,
  },
  departmentImage: {
    width: '100%',
    height: 130,
    borderRadius: 10,
    marginBottom: 12,
  },
  homeLabel: {
    fontSize: 12,
    color: '#667085',
    marginTop: 4,
  },
  homeValue: {
    fontSize: 16,
    color: '#101828',
    fontWeight: '600',
    marginTop: 2,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#101828',
    marginBottom: 10,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: '#d0d5dd',
    borderRadius: 10,
    paddingVertical: 11,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  secondaryButtonText: {
    color: '#344054',
    fontWeight: '600',
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  glyphBadge: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  glyphText: {
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 24,
  },
  settingsRow: {
    borderWidth: 1,
    borderColor: '#d0d5dd',
    borderRadius: 10,
    paddingVertical: 11,
    paddingHorizontal: 12,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logoutButton: {
    marginTop: 4,
    borderRadius: 10,
    paddingVertical: 12,
    backgroundColor: '#b42318',
    alignItems: 'center',
  },
});
